// export { default as css } from "./css-logo.svg";
// export { default as django } from "./django-logo.svg";
// export { default as docker } from "./docker-logo.svg";
// export { default as firebase } from "./firebase-logo.svg";
// export { default as node } from "./node-logo.svg";
// export { default as postgres } from "./postgres-logo.svg";
// export { default as react } from "./react-logo.svg";
// export { default as git } from "./git-logo.svg";
// export { default as mongo } from "./mongo-logo.svg";
// export { default as ts } from "./ts-logo.svg";
// export { default as python } from "./python-logo.svg";
// export { default as styledComponents } from "./styled-components-logo.svg";
// export { default as nixos } from "./nixos-logo.svg";
export { default as css } from "../../assets/svg/css-logo.svg?url";
export { default as django } from "../../assets/svg/django-logo.svg?url";
// export { default as docker } from "../../assets/svg/docker-logo.svg?url";
// export { default as firebase } from "../../assets/svg/firebase-logo.svg?url";
// export { default as node } from "../../assets/svg/node-logo.svg?url";
export { default as postgres } from "../../assets/svg/postgres-logo.svg?url";
// export { default as react } from "../../assets/svg/react-logo.svg?url";
// export { default as git } from "../../assets/svg/git-logo.svg?url";
// export { default as mongo } from "../../assets/svg/mongo-logo.svg?url";
export { default as ts } from "../../assets/svg/typescript-logo.svg?url";
export { default as python } from "../../assets/svg/python-logo.svg?url";